---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: ghcr.io/cloudfoundry/app-autoscaler-ci-deploy
    tag: master
inputs:
  - name: ops-files
  - name: custom-ops
  - name: app-autoscaler-ci
outputs:
  - name: combined-ops
run:
  path: app-autoscaler-ci/autoscaler/scripts/combine-ops.sh
