---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ghcr.io/cloudfoundry/app-autoscaler-ci-deploy
    tag: master

params:
  SYSTEM_DOMAIN:
  SERVICE_OFFERING_ENABLED: false
  SKIP_SSL_VALIDATION: false

inputs:
- name: bbl-state
- name: app-autoscaler-release
- name: app-autoscaler-ci

outputs:

run:
  path: app-autoscaler-ci/autoscaler/scripts/register-broker.sh
