---
platform: linux

image_resource:
  type: docker-image
  source: 
    repository: ghcr.io/cloudfoundry/app-autoscaler-ci-deploy
    tag: master

params:
  # if set to false, the bosh release will be skipped and only the changelog & next version generated
  PERFORM_BOSH_RELEASE: true

inputs:
- name: app-autoscaler-release
- name: app-autoscaler-ci
- name: gh-release

outputs:
- name: generated-release

run:
  path: app-autoscaler-ci/autoscaler/scripts/release-autoscaler.sh
